"use client";

import { BellRing, CheckCheck, Clock3, Eye, LoaderCircle, Mail, Search, Trash2 } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import type { NotificationEvent, NotificationPreferences, SavedSearch } from "@/lib/types";

export function InboxWorkspace({ initialEvents, initialPreferences, initialSearches }: { initialEvents: NotificationEvent[]; initialPreferences: NotificationPreferences; initialSearches: SavedSearch[] }) {
  const [events, setEvents] = useState(initialEvents);
  const [preferences, setPreferences] = useState(initialPreferences);
  const [searches, setSearches] = useState(initialSearches);
  const [busy, setBusy] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  async function savePreferences(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy("preferences"); setMessage(null);
    const form = new FormData(event.currentTarget);
    const payload = { email_enabled: form.has("email_enabled"), immediate_strong: form.has("immediate_strong"), daily_digest: form.has("daily_digest"), deadline_reminders: form.has("deadline_reminders"), deadline_offsets: form.getAll("deadline_offsets").map(Number), digest_hour: Number(form.get("digest_hour")) };
    const response = await fetch("/api/notifications", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) });
    const data = await response.json() as { preferences?: NotificationPreferences; error?: string };
    if (data.preferences) setPreferences(data.preferences);
    setMessage(response.ok ? "Preferências de alerta salvas." : data.error || "Falha ao salvar."); setBusy(null);
  }
  async function markAll() { setBusy("read"); await fetch("/api/notifications", { method: "PATCH" }); setEvents((current) => current.map((item) => ({ ...item, read_at: new Date().toISOString() }))); setBusy(null); }
  async function dismiss(id: string) { await fetch(`/api/notifications/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: '{"dismissed":true}' }); setEvents((current) => current.filter((item) => item.id !== id)); }
  async function addSearch(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy("search"); const form = event.currentTarget; const data = new FormData(form);
    const payload = { name: data.get("name"), notify: data.has("notify"), filters: { q: data.get("q") || "", mode: data.get("mode") || "", score: data.get("score") || "0", tier: "radar" } };
    const response = await fetch("/api/saved-searches", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) });
    const result = await response.json() as { search?: SavedSearch; error?: string };
    if (result.search) { setSearches((current) => [result.search!, ...current]); form.reset(); }
    setMessage(response.ok ? "Busca salva." : result.error || "Falha ao salvar busca."); setBusy(null);
  }
  async function removeSearch(id: string) { await fetch(`/api/saved-searches/${id}`, { method: "DELETE" }); setSearches((current) => current.filter((item) => item.id !== id)); }
  return <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]">
    <section className="surface overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-[var(--line)] bg-[var(--ink)] p-5 text-white"><div><p className="eyebrow text-[var(--acid)]">Caixa de entrada</p><h2 className="mt-2 text-2xl font-semibold">Sinais que merecem atenção</h2></div><button onClick={markAll} disabled={busy === "read"} className="inline-flex min-h-11 items-center gap-2 px-3 text-sm font-semibold text-[var(--acid)]"><CheckCheck size={17} />Marcar como lidas</button></div>
      {!events.length ? <div className="grid min-h-64 place-items-center p-8 text-center"><BellRing className="mx-auto text-[var(--green)]" size={34} /><p className="mt-4 font-semibold">Tudo acompanhado por aqui</p><p className="mt-1 text-sm text-[var(--ink-soft)]">Novas vagas fortes, atualizações e prazos aparecerão nesta caixa.</p></div> : <div className="divide-y divide-[var(--line)]">{events.map((event) => { const href = typeof event.payload.href === "string" ? event.payload.href : "/"; return <article key={event.id} className={`grid gap-4 p-5 sm:grid-cols-[44px_1fr_auto] ${event.read_at ? "opacity-65" : "bg-white"}`}><span className={`grid size-11 place-items-center ${event.event_type === "deadline" ? "bg-[#fff0bf] text-[var(--amber)]" : "bg-[#e8f5ef] text-[var(--green)]"}`}>{event.event_type === "deadline" ? <Clock3 size={19} /> : <BellRing size={19} />}</span><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{event.title}</p>{event.status === "preview" && <span className="eyebrow bg-[var(--paper)] px-2 py-1 text-[9px]">prévia de e-mail</span>}</div><p className="mt-1 text-sm text-[var(--ink-soft)]">{event.body}</p><p className="mono mt-2 text-[10px] text-[var(--ink-soft)]">{new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(event.created_at))}</p></div><div className="flex items-center gap-1"><Link href={href} className="grid size-11 place-items-center text-[var(--green)]" title="Abrir"><Eye size={17} /></Link><button onClick={() => dismiss(event.id)} className="grid size-11 place-items-center text-[var(--red)]" title="Dispensar alerta"><Trash2 size={17} /></button></div></article>; })}</div>}
    </section>
    <aside className="grid h-fit gap-6 xl:sticky xl:top-8"><section className="surface overflow-hidden"><div className="border-b border-[var(--line)] bg-white p-5"><Mail className="text-[var(--green)]" size={23} /><h2 className="mt-3 text-xl font-semibold">Alertas pessoais</h2><p className="mt-1 text-sm text-[var(--ink-soft)]">O envio começa em modo de pré-visualização.</p></div><form onSubmit={savePreferences} className="grid gap-4 p-5">{[["email_enabled", "Receber por e-mail"], ["immediate_strong", "Vagas fortes imediatamente"], ["daily_digest", "Resumo diário"], ["deadline_reminders", "Lembretes de prazo"]].map(([name, label]) => <label key={name} className="flex items-center gap-3"><input type="checkbox" name={name} defaultChecked={Boolean(preferences[name as keyof NotificationPreferences])} /><span className="text-sm font-medium">{label}</span></label>)}<div><span className="eyebrow text-[var(--ink-soft)]">Lembrar antes do prazo</span><div className="mt-2 flex gap-3">{[7, 3, 1].map((day) => <label key={day} className="flex items-center gap-1.5 text-sm"><input type="checkbox" name="deadline_offsets" value={day} defaultChecked={preferences.deadline_offsets.includes(day)} />{day}d</label>)}</div></div><label><span className="eyebrow text-[var(--ink-soft)]">Hora do resumo</span><input className="field mt-2" name="digest_hour" type="number" min="0" max="23" defaultValue={preferences.digest_hour} /></label><button className="button-dark" disabled={busy === "preferences"}>{busy === "preferences" ? <LoaderCircle className="animate-spin" size={17} /> : <Mail size={17} />}Salvar alertas</button></form></section>
      <section className="surface overflow-hidden"><div className="border-b border-[var(--line)] p-5"><Search className="text-[var(--green)]" size={22} /><h2 className="mt-3 text-xl font-semibold">Buscas salvas</h2></div><form onSubmit={addSearch} className="grid gap-3 p-5"><input className="field" name="name" required placeholder="Nome da busca" /><input className="field" name="q" placeholder="Cargo ou tecnologia" /><div className="grid grid-cols-2 gap-3"><select className="field" name="mode"><option value="">Qualquer modelo</option><option value="remote">Remoto</option><option value="hybrid">Híbrido</option><option value="onsite">Presencial</option></select><select className="field" name="score"><option value="0">Qualquer score</option><option value="60">60+</option><option value="80">80+</option></select></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="notify" defaultChecked />Alertar novidades</label><button className="button-light" disabled={busy === "search"}>Salvar busca</button></form><div className="divide-y divide-[var(--line)]">{searches.map((search) => { const params = new URLSearchParams(Object.entries(search.filters).map(([key, value]) => [key, String(value)])); return <div key={search.id} className="flex items-center gap-2 p-4"><Link href={`/?${params}`} className="min-w-0 flex-1 font-semibold hover:underline">{search.name}</Link><button onClick={() => removeSearch(search.id)} className="grid size-10 place-items-center text-[var(--red)]" title="Excluir"><Trash2 size={16} /></button></div>; })}</div></section>
      {message && <p className="border-l-4 border-[var(--green)] bg-white p-3 text-sm" role="status">{message}</p>}
    </aside>
  </div>;
}
