import type { Job } from "./types";

export const demoJobs: Job[] = [
  {
    id: "demo-1",
    title: "Estágio em Machine Learning",
    company: "Nubank",
    description: "Time de modelos de risco busca estudante com Python, SQL e fundamentos de machine learning.",
    location: "São Paulo, SP",
    work_mode: "hybrid",
    source: "LinkedIn",
    source_url: "https://www.linkedin.com/jobs/",
    published_at: "2026-08-07T11:00:00.000Z",
    discovered_at: "2026-08-07T12:30:00.000Z",
    score: 94,
    score_reasons: ["machine learning no título", "São Paulo", "nível estágio"],
    status: "new",
    match_area: true,
    match_location: true,
    match_start: true,
    display_tier: "strong",
    target_fit: "confirmed",
    location_fit: "confirmed",
    display_reasons: ["ciclo e localização compatíveis"],
  },
  {
    id: "demo-2",
    title: "Programa de Estágio — Data & Analytics",
    company: "Itaú Unibanco",
    description: "Vaga para atuar com análise de dados, dashboards e automações em ambiente híbrido.",
    location: "São Paulo, SP",
    work_mode: "hybrid",
    source: "Gupy",
    source_url: "https://portal.gupy.io/",
    published_at: "2026-08-06T14:00:00.000Z",
    discovered_at: "2026-08-07T08:15:00.000Z",
    score: 88,
    score_reasons: ["data & analytics", "programa de estágio", "modelo híbrido"],
    status: "saved",
    match_area: true,
    match_location: true,
    match_start: false,
    display_tier: "watchlist",
    target_fit: "unknown",
    location_fit: "confirmed",
    display_reasons: ["ano de início não informado"],
  },
  {
    id: "demo-3",
    title: "Data Science Intern",
    company: "Wildlife Studios",
    description: "Remote internship working with experimentation, product analytics and predictive models.",
    location: "Brasil",
    work_mode: "remote",
    source: "Careers",
    source_url: "https://wildlifestudios.com/careers/",
    published_at: "2026-08-05T09:00:00.000Z",
    discovered_at: "2026-08-07T07:40:00.000Z",
    score: 85,
    score_reasons: ["data science", "intern", "remoto Brasil"],
    status: "new",
    match_area: true,
    match_location: true,
    match_start: false,
    display_tier: "watchlist",
    target_fit: "unknown",
    location_fit: "confirmed",
    display_reasons: ["ano de início não informado"],
  },
  {
    id: "demo-4",
    title: "Estágio em Engenharia de Dados",
    company: "Mercado Livre",
    description: "Construção de pipelines, qualidade de dados e apoio ao time de engenharia.",
    location: "Osasco, SP",
    work_mode: "hybrid",
    source: "Indeed",
    source_url: "https://br.indeed.com/",
    published_at: "2026-08-04T17:00:00.000Z",
    discovered_at: "2026-08-06T10:00:00.000Z",
    score: 76,
    score_reasons: ["engenharia de dados", "estágio", "região de São Paulo"],
    status: "applied",
    match_area: true,
    match_location: true,
    match_start: false,
    display_tier: "watchlist",
    target_fit: "unknown",
    location_fit: "confirmed",
    display_reasons: ["ano de início não informado"],
  },
];
