import { ArrowLeft, ArrowUpRight, Banknote, BookOpenCheck, BriefcaseBusiness, CalendarClock, Clock3, Files, GraduationCap, MapPin, ShieldCheck, Sparkles } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { SaveJobButton } from "@/components/save-job-button";
import { getJobDetail } from "@/lib/job-data";

const date = (value?: string | null) => value ? new Intl.DateTimeFormat("pt-BR", { timeZone: "America/Sao_Paulo", dateStyle: "long" }).format(new Date(value)) : "Não informado";
const money = (value?: number | null) => value ? new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL", maximumFractionDigits: 0 }).format(value) : null;

export default async function JobDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const detail = await getJobDetail(id);
  if (!detail) notFound();
  const { job, match } = detail;
  const applyUrl = job.application_url || job.official_url || job.source_url;
  const salary = job.salary_min ? job.salary_max && job.salary_max !== job.salary_min ? `${money(job.salary_min)} – ${money(job.salary_max)}` : money(job.salary_min) : null;
  return <main id="conteudo" className="shell pb-20 pt-8">
    <Link href="/" className="mb-6 inline-flex min-h-11 items-center gap-2 font-semibold text-[var(--green)] hover:underline"><ArrowLeft size={17} />Voltar ao radar</Link>
    <header className="relative overflow-hidden border border-[var(--ink)] bg-[var(--ink)] p-6 text-white sm:p-9"><div className="absolute right-0 top-0 size-40 translate-x-12 -translate-y-16 rotate-12 bg-[var(--acid)] opacity-90" /><div className="relative max-w-4xl"><div className="flex flex-wrap gap-2"><span className="eyebrow bg-[var(--acid)] px-2 py-1 text-[var(--ink)]">{job.display_tier === "strong" ? "Vaga confirmada" : job.candidate_kind === "lead" ? "Lead a confirmar" : "Vaga em análise"}</span><span className="eyebrow border border-white/20 px-2 py-1 text-white/70">{job.source}</span></div><p className="eyebrow mt-7 text-[var(--acid)]">{job.company}</p><h1 className="mt-2 text-4xl font-bold tracking-[-.06em] sm:text-6xl">{job.title}</h1><div className="mt-6 flex flex-wrap gap-x-6 gap-y-2 text-sm text-white/70"><span className="flex items-center gap-2"><MapPin size={16} />{job.location || "Localização não informada"}</span><span className="flex items-center gap-2"><CalendarClock size={16} />Prazo: {date(job.application_deadline)}</span><span className="flex items-center gap-2"><Files size={16} />{job.job_sources.length} fonte{job.job_sources.length === 1 ? "" : "s"}</span></div></div></header>
    <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_340px]">
      <div className="grid gap-6"><section className="surface p-6 sm:p-8"><p className="eyebrow text-[var(--green)]">Descrição consolidada</p><div className="mt-4 whitespace-pre-line text-[15px] leading-7 text-[var(--ink-soft)]">{job.description || "A fonte não forneceu uma descrição completa."}</div></section>
        <div className="grid gap-6 md:grid-cols-2"><ListSection icon={BriefcaseBusiness} title="Responsabilidades" values={job.responsibilities || []} empty="Responsabilidades não extraídas." /><ListSection icon={BookOpenCheck} title="Requisitos" values={job.requirements || []} empty="Requisitos não extraídos." /><ListSection icon={GraduationCap} title="Formação" values={job.education_requirements || []} empty="Formação não informada." /><ListSection icon={Sparkles} title="Competências" values={job.extracted_skills || []} empty="Competências não extraídas." /></div>
        {match && <section className="surface overflow-hidden"><div className="bg-[var(--green)] p-6 text-white"><p className="eyebrow text-white/60">Aderência ao seu perfil</p><div className="mt-2 flex items-end gap-4"><span className="mono text-5xl font-semibold">{match.final_score}</span><p className="pb-1 text-white/75">{match.summary}</p></div></div><div className="grid gap-5 p-6 md:grid-cols-3"><List title="Pontos fortes" values={match.strengths} /><List title="Lacunas" values={match.gaps} /><List title="Atenções" values={match.concerns} /></div></section>}
        <section className="surface overflow-hidden"><div className="border-b border-[var(--line)] p-6"><p className="eyebrow text-[var(--green)]">Rastreabilidade</p><h2 className="mt-2 text-2xl font-semibold">Fontes preservadas</h2></div><div className="divide-y divide-[var(--line)]">{job.job_sources.map((source) => <a key={source.id} href={source.source_url} target="_blank" rel="noreferrer" className="flex min-h-16 items-center justify-between gap-4 p-5 hover:bg-white"><span><strong>{source.source}</strong><span className="mt-1 block text-xs text-[var(--ink-soft)]">Vista de {date(source.first_seen_at)} até {date(source.last_seen_at)}</span></span><ArrowUpRight size={17} /></a>)}</div></section>
      </div>
      <aside className="grid h-fit gap-4 xl:sticky xl:top-8"><section className="surface p-5"><div className="grid grid-cols-2 gap-3"><Fact icon={Banknote} label="Bolsa" value={salary || "Não informada"} /><Fact icon={Clock3} label="Carga" value={job.workload_hours_week ? `${job.workload_hours_week}h/semana` : "Não informada"} /><Fact icon={Sparkles} label="Score" value={`${job.score}/100`} /><Fact icon={ShieldCheck} label="Qualidade" value={`${job.quality_score || 0}/100`} /></div><a href={applyUrl} target="_blank" rel="noreferrer" className="button-dark mt-5 w-full justify-center">Candidatar-se <ArrowUpRight size={17} /></a><div className="mt-2"><SaveJobButton jobId={job.id} authenticated={detail.authenticated} initiallySaved={detail.saved} /></div></section>
        <section className="border-l-4 border-[var(--acid)] bg-white p-5"><p className="eyebrow">Histórico</p><p className="mt-3 text-sm">Encontrada em <strong>{date(job.first_seen_at || job.discovered_at)}</strong></p><p className="mt-2 text-sm">Vista pela última vez em <strong>{date(job.last_seen_at)}</strong></p>{job.content_changed_at && <p className="mt-2 text-sm">Conteúdo alterado em <strong>{date(job.content_changed_at)}</strong></p>}</section>
        {(job.benefits || []).length > 0 && <section className="surface p-5"><p className="eyebrow text-[var(--green)]">Benefícios</p><div className="mt-3 flex flex-wrap gap-2">{job.benefits!.map((benefit) => <span key={benefit} className="border border-[var(--line)] bg-white px-2 py-1 text-sm">{benefit}</span>)}</div></section>}
      </aside>
    </div>
  </main>;
}

function ListSection({ icon: Icon, title, values, empty }: { icon: typeof BriefcaseBusiness; title: string; values: string[]; empty: string }) { return <section className="surface p-6"><Icon className="text-[var(--green)]" size={22} /><h2 className="mt-4 text-xl font-semibold">{title}</h2>{values.length ? <ul className="mt-4 space-y-2 text-sm leading-relaxed text-[var(--ink-soft)]">{values.map((value) => <li key={value} className="border-l-2 border-[var(--acid)] pl-3">{value}</li>)}</ul> : <p className="mt-3 text-sm text-[var(--ink-soft)]">{empty}</p>}</section>; }
function List({ title, values }: { title: string; values: string[] }) { return <div><p className="eyebrow text-[var(--green)]">{title}</p><ul className="mt-3 space-y-2 text-sm text-[var(--ink-soft)]">{values.length ? values.map((value) => <li key={value}>• {value}</li>) : <li>Sem dados suficientes.</li>}</ul></div>; }
function Fact({ icon: Icon, label, value }: { icon: typeof Banknote; label: string; value: string }) { return <div className="border border-[var(--line)] bg-white p-3"><Icon className="text-[var(--green)]" size={17} /><span className="eyebrow mt-3 block text-[var(--ink-soft)]">{label}</span><strong className="mt-1 block text-sm">{value}</strong></div>; }
